[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mining_v2 = "uaDkkJGLLEY3kFMhhvrh5MZJ6fmwCmhNf8L7BZQJ9Aw"

[programs.mainnet]
mining_v2 = "uaDkkJGLLEY3kFMhhvrh5MZJ6fmwCmhNf8L7BZQJ9Aw"
melt_v1 = "HAWdiMtvTfiFhENgxPdWEgBQmoa3A5oN1KV9N3LSmxXz"

[programs.testnet]
mining_v2 = "uaDkkJGLLEY3kFMhhvrh5MZJ6fmwCmhNf8L7BZQJ9Aw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.mainnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 60000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 200000 tests/**/*.ts"
